#define FOREACH_TOKEN(TOKEN) \
	TOKEN(END) \
  TOKEN(INVALID) \
  TOKEN(NUMBER) \
  TOKEN(HEXADECIMAL) \
  TOKEN(TEXT) \
  TOKEN(CHAR) \
  TOKEN(COMMENT) \
  TOKEN(TK_ID) \
  TOKEN(TK_INT) \
  TOKEN(TK_CHAR) \
  TOKEN(TK_FLOAT) \
  TOKEN(TK_VOID) \
  TOKEN(TK_IF) \
  TOKEN(TK_ELSE) \
  TOKEN(TK_WHILE) \
  TOKEN(TK_NEW) \
  TOKEN(TK_RETURN) \

#define GENERATE_ENUM(ENUM) ENUM,
#define GENERATE_STRING(STRING) #STRING,

enum {
	FOREACH_TOKEN(GENERATE_ENUM)
} token;

static const char *TOKEN_STR[] = {
	FOREACH_TOKEN(GENERATE_STRING)
};

union {
	long long int ival;
	char *text;
} yylval;
